FAILOVER CLUSTERING STEPS===============================================================

EXTRACT THE WIN SERVER FILES FROM THE FOLDER 
OPEN THE FILE WITH DIFFERENT LOGO WITH WORKSTATION PRO
START THE VIRTUAL MACHINE
WHEN ON SIGN IN PAGE . CLICK ON THE ABOVE 3 BOXES LIKE BUTTON WHICH IS ALT DEL 
CLICK ON ADMINSTRATOR ACCOUNT
CLICK AND MAKE NEW PASSWORD admin@123
CLICK AND ADD ROLE AND FEATURES
CLICK ON NEXT
SELECT ROLE BASED OR FEATURE BASED INSTALLTION
CLICK ON NEXT
IN SERVER ROLES SELECT > ACTIVE DIRECTORY DOMAIN SERVICES>DHCP SERVER>DNS SERVER>CLICK ON NEXT
IN FEATURES SELECT > FAILOVER CLUSTERING > GROUP POLICY MANAGEMENT
CLICK ON NEXT TILL CONFIRMATION
THEN CLICK ON EXPORT SETTINGS
THEN RIGHT CLICK ON THE ORIGINAL VM TASK HEADING AND GO INTO SETTING(THE BAR FROM WEERE YOU CAN RESTART THE VM)
GO INTO THE CD/DVD
IN LEFT> SELECT>USE ISO IMGAE FILE>SELECT EN_WINDOWS_SERVER>CLICK ON CONNECTEED ABOVE
NOW AGAIN GO TO EXPORT CONFIGURATION
GO TO D DRIVE WHCIH WE CAN SEE NOW> GO TO D:/SOURCES/SXS
COPY THIS PATH
COME BACK TO EXPORRT SETTTING>CLICK ON SPECIFY ALTERNTE SOURCE PATH>CLICK ON OK
CLICK ON INSTALL
RESTART THE HOST MACHINE
CLICK ON THE TOOLS ABOVE RIGHT CORNER > CLICK ON FAILOVER CLUSTER MNAGER
COMEBACK TO MAIN PAGE AND THEN CLICK ON THE ADDS AND CLICK ON THE MORE FROM ABOVE
CLICK ON PROMOTE THIS SERVER
ACTIVE DIRECTORY DOMAIN SERVICES CONFIGURATION WIZARD> SELECT ADD A NEW FRIEND
ROOT DOMAIN NAME SIES.COM>
GIVE A PASSWORD GENERALLY KEEP IT SAME
NEXT
CLICK ALL THE NEXT AND INSTALL > RESTART AND LOGIN
TOOL>FAILOVER CLIUSTER MANAGEMENT
CLICK ON CREATECLUSTER
CREATE A CLUSTER WIZARD
NEXT STEP CLICK ON BROWSE AND THEN CLCKN ON ADVANCE> CLICK ON FIND NOW>SELECT OUR CLUTER > GIVE THE CLUSTER NAME > SELECT NO IN VALIDATION> AGAIN GIVE CLUSTER NAME
THWEN WE CAN SEE THAT THE CLUSTER

VMWARE ESXI SERVER AND MANAGING WITH VPSHER CLIENT ================================
